### PR TITLE
Fixes #3 Made the xml file of sign up page of digigate

### LINKED ISSUE #3: XML Layout for SignUp Activity
### Is your feature request related to a problem? Please describe.

Create a XML layout for sign up activity based on the design specifications given in [Readme](https://github.com/bsoc-bitbyte/DigiGate/blob/main/README.md#design) file.

### Points to be consider:
1. Use Constraint Layout.
2. The layout should follow the general design specifications with reasonable padding and margin values chosen by the contributor.

### Describe the solution you'd like

I would like to have an XML layout file (`res/layout/activity_sign_up.xml`) for the SignUp Activity that includes all the necessary UI elements as described above. The layout should:

 The XML layout should be implemented in `res/layout/activity_sign_up.xml`.
- The layout should match the general design specifications provided in the README file.
- The layout should use appropriate padding and margin values chosen by the contributor.
- The layout should be visually consistent with the design mockup provided in the README file.

### Describe alternatives you've considered

_No response_

### Developer Help

_No response_

### PR DESCRIPTION
**Pull request by AyushNarsian**
1. This PR fixes or fixes part of #3 
2. This PR does the following:
 This PR modifies the sign up page as expected and adds the desired drawable files.
## Essential Checklist

- [x ] The PR title starts with "Fix #bugnum: ", followed by a short, clear summary of the changes. (If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...".)
- [ x] "Allow edits from maintainers" is checked. (See [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) for instructions on how to enable it.)

## Proof that changes are correct
Screenshot 2024-06-04 172203

## PR Pointers

- If you need a review or an answer to a question, and don't have permissions to assign people, **leave a comment** like the following: "{{Question/comment}} @{{reviewer_username}} PTAL".
- Never force push. If you do, your PR will be closed.

### CODE REVIEW

**Review by aarav0012 — CHANGES_REQUESTED** [review]
1. increase padding ang margin between components according to figma.
2. decrease the size of email icon.
3. make it more visually appealing.

**Comment by AyushNarsian** [comment]
Done all the necessary changes. Also made the page responsive to different screen sizes and done some necessary changes in icon size fonts, padding and margin to make the page more visually appealing.
Also added some gap between hostel and room no. box like figma file.

Screenshot 2024-06-05 013920

**Comment by aarav0012** [comment]
image

background is divided in two part, modify it

**Comment by AyushNarsian** [comment]
The background has been fixed and dimensions of everything is a multiple of 4 except the hint text size and also added some gaps among all the edit textboxes to make it look more organized and like the figma.
Screenshot 2024-06-05 170649

**Review by aarav0012 — COMMENTED** [review]
use constraint layout and bind each element with each other or with parent no need to use linear layout

**Comment by AyushNarsian** [comment]
Made the desired changes and removed the linear layout

**Review by aarav0012 — APPROVED** [review]
LGTM

**Pull request merged**
